name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@v5
        env:
          BUILDKIT_PROGRESS: plain
        with:
          context: .
          file: ./Dockerfile
          push: false
          no-cache: true
          tags: ocr-app:test

      - name: Save image as tar
        run: docker save ocr-app:test -o ocr-app-test.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ocr-app-test
          path: ocr-app-test.tar
